prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="American Samoa [United States]"]                  <- "American Samoa"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Bahamas, The"]                                    <- "Bahamas"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Bermuda [United Kingdom]"]                        <- "Bermuda"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="British Indian Ocean Territory [United Kingdom]"] <- "British Indian Ocean Territory"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Brunei"]                                          <- "Brunei Darussalam"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Cayman Islands [United Kingdom]"]                 <- "Cayman Islands"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Christmas Island [Australia]"]                    <- "Christmas Island"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Cocos (Keeling) Islands [Australia]"]             <- "Cocos (Keeling) Islands"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Congo (Kinshasa)"]                                <- "Congo"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Cook Islands [New Zealand]"]                      <- "Cook Islands"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Cote D'Ivoire"]                                   <- "Cote d'Ivoire"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Congo (Brazzaville)"]                             <- "Democratic Republic of the Congo"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Falkland Islands (Islas Malvinas) [United Kingd"] <- "Falkland Islands (Malvinas)"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="French Guiana [France]"]                          <- "French Guiana"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="French Southern and Antarctic Lands [France]"]    <- "French Southern and Antarctic Lands"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Gambia, The"]                                     <- "Gambia"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Gibraltar [United Kingdom]"]                      <- "Gibraltar"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Greenland [Denmark]"]                             <- "Greenland"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Guadeloupe [France]"]                             <- "Guadeloupe"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Guam [United States]"]                            <- "Guam"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Iran"]                                            <- "Iran (Islamic Republic of)"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Jan Mayen [Norway]"]                              <- "Isle of Man"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Korea, North"]                                    <- "Korea, Democratic People's Republic of"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Korea, South"]                                    <- "Korea, Republic of"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Laos"]                                            <- "Lao People's Democratic Republic"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Libya"]                                           <- "Libyan Arab Jamahiriya"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Macau S.A.R"]                                     <- "Macau"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Martinique [France]"]                             <- "Martinique"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Mayotte [France]"]                                <- "Mayotte"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Federated States of Micronesia"]                  <- "Micronesia, Federated States of"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="New Caledonia [France]"]                          <- "New Caledonia"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Niue [New Zealand]"]                              <- "Niue"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Norfolk Island [Australia]"]                      <- "Norfolk Island"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Northern Mariana Islands [United States]"]        <- "Northern Mariana Islands"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Puerto Rico [United States]"]                     <- "Puerto Rico"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Moldova"]                                         <- "Republic of Moldova"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Reunion [France]"]                                <- "Reunion"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Saint Helena [United Kingdom]"]                   <- "Saint Helena"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Sint Maarten"]                                    <- "Saint Martin"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Saint Pierre and Miquelon [France]"]              <- "Saint Pierre and Miquelon"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Svalbard [Norway]"]                               <- "Saint Vincent and the Grenadines"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="South Georgia and the South Sandwich Islands [U"] <- "South Georgia South Sandwich Islands"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Syria"]                                           <- "Syrian Arab Republic"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Tokelau [New Zealand]"]                           <- "Tokelau"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Tanzania"]                                        <- "United Republic of Tanzania"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Wake Island [United States]"]                     <- "United States Minor Outlying Islands"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Virgin Islands [United States]"]                  <- "United States Virgin Islands"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Vietnam"]                                         <- "Viet Nam"
prcp$COUNTRY_NAME[prcp$COUNTRY_NAME=="Wallis and Futuna [France]"]                      <- "Wallis and Futuna Islands"